# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: contracts changed
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 17]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with: { fetch-depth: 0 }
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Checkout Specmatic JMS Repo
      uses: actions/checkout@v3
      with:
        repository: znsio/specmatic-jms
        path: specmatic-jms
        token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

    - name: Grant execute permission for gradlew
      working-directory: specmatic-jms
      run: chmod +x gradlew

    - name: Publish Specmatic JMS to Local Maven Repo
      working-directory: specmatic-jms
      run: ./gradlew publishToMavenLocal

    - name: Grant execute permission for gradlew on BFF repo
      run: chmod +x gradlew

    - name: Build BFF project with Gradle
      run: ./gradlew build

    - name: Run coverage report
      run: ./gradlew jacocoTestReport

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
      if: matrix.os == 'ubuntu-latest'

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
  
      
